<?php

namespace AppBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche des trois dernières actualités
     * 
     * author: Delrodie AMOIKON
     * date: 20/01/2018 00:48
     */
    public function findLastActualite($offset, $limit)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT a, t
                            FROM AppBundle:Actualite a
                            LEFT JOIN a.typactualite t
                            WHERE a.statut = :actif
                            ORDER BY a.id DESC
                        ')
                        ->setFirstResult($offset)
                        ->setMaxresults($limit)
                        ->setParameter('actif', 1)
                        ->getResult()
                        ;
    }
    
    /**
     * Recherche des trois dernières actualités sans la concernée
     * 
     * author: Delrodie AMOIKON
     * date: 20/01/2018 02:41
     */
    public function findThreeLastActualite($slug, $offset, $limit)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT a, t
                            FROM AppBundle:Actualite a
                            LEFT JOIN a.typactualite t
                            WHERE a.statut = :actif
                            AND a.slug <> :slug
                            ORDER BY a.id DESC
                        ')
                        ->setFirstResult($offset)
                        ->setMaxresults($limit)
                        ->setParameters(array(
                            'actif' => 1,
                            'slug'  => $slug
                        ))
                        ->getResult()
                        ;
    }
}
