<?php

namespace AppBundle\Repository;

/**
 * AdulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdulteRepository extends \Doctrine\ORM\EntityRepository
{
}
