<?php

namespace AppBundle\Repository;

/**
 * AdulteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdulteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche des trois dernières actualités sans la concernée
     * 
     * author: Delrodie AMOIKON
     * date: 25/01/2018 02:57
     */
    public function findAdulte($slug)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT a, b
                            FROM AppBundle:Adulte a
                            LEFT JOIN a.chef b
                            WHERE a.statut = :actif
                            AND b.slug LIKE :slug
                        ')
                        ->setParameters(array(
                            'actif' => 1,
                            'slug'  => '%'.$slug.'%'
                        ))
                        ->getResult()
                        ;
    }
}
