<?php

namespace AppBundle\Repository;

/**
 * BlockCampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockCampRepository extends \Doctrine\ORM\EntityRepository
{
}
