<?php

namespace AppBundle\Repository;

/**
 * BrandboutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandboutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
