<?php

namespace AppBundle\Repository;

/**
 * CouvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouvertureRepository extends \Doctrine\ORM\EntityRepository
{
}
