<?php

namespace AppBundle\Repository;

/**
 * Departement2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Departement2Repository extends \Doctrine\ORM\EntityRepository
{
}
