<?php

namespace AppBundle\Repository;

/**
 * EnvolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvolRepository extends \Doctrine\ORM\EntityRepository
{
}
