<?php

namespace AppBundle\Repository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche u membre de l'equipe nationale correspondant au slug
     * 
     * author: Delrodie AMOIKON 
     * date: 10/02/2018 09:50
     */
    public function findMembre($slug)
    {
        $em = $this->getEntityManager();
        $q = $em->createQuery('
                        SELECT e
                        FROM AppBundle:Equipe e
                        WHERE e.statut = 1
                        AND e.slug LIKE :slug
                    ')
                    ->setMaxResults(1)
                    ->setParameter('slug', '%'.$slug.'%')
                    ;
            if (!$q->getResult()){
                return $q->getResult();
            }else{
                return $q->getSingleResult();
            }
    }

    /**
     * Listes des membres de l'equipe nationale par statut
     *
     * author: Delrodie AMOIKON
     * date: 10/02/2018 11:34
     */
    public function findMembreByTypefonction($slug)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                        SELECT e, t
                        FROM AppBundle:Equipe e
                        LEFT JOIN e.typefonction t
                        WHERE e.statut = 1
                        AND t.slug LIKE :slug
                    ')
                    ->setParameter('slug', '%'.$slug.'%')
                    ->getResult()
                    ;
    }

    /**
     * Liste des commissaires nationaux à l'international
     *
     * author: Delrodie AMOIKON
     * date 06/04/2018 18:54
     */
    public function findMembreByDepartement($slug)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                        SELECT e, d
                        FROM AppBundle:Equipe e
                        LEFT JOIN e.departement d
                        WHERE e.statut = 1
                        AND d.slug LIKE :slug
                    ')
                    ->setParameter('slug', '%'.$slug.'%')
                    ->getResult()
                ;
    }
}
