<?php

namespace AppBundle\Repository;

/**
 * FacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recuperation du dernier enregistrement
     */
    public function findLastFacebook()
    {
        return $this->createQueryBuilder('f')
                    ->orderBy('f.id', 'DESC')
                    ->setFirstResult(0)
                    ->setMaxResults(1)
                    ->getQuery()->getResult();
        ;
    }
}
