<?php

namespace AppBundle\Repository;

/**
 * FondsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FondsRepository extends \Doctrine\ORM\EntityRepository
{
}
