<?php

namespace AppBundle\Repository;

/**
 * InternationaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternationaleRepository extends \Doctrine\ORM\EntityRepository
{
}
