<?php

namespace AppBundle\Repository;

/**
 * InternationaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternationaleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche des trois dernières actualités internationales
     * 
     * author: Delrodie AMOIKON
     * date: 20/01/2018 01:48
     */
    public function findLastInternationale($offset, $limit)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT i
                            FROM AppBundle:Internationale i
                            WHERE i.statut = :actif
                            ORDER BY i.id DESC
                        ')
                        ->setFirstResult($offset)
                        ->setMaxresults($limit)
                        ->setParameter('actif', 1)
                        ->getResult()
                        ;
    }

    /**
     * Recherche des trois dernières actualités sans la concernée
     * 
     * author: Delrodie AMOIKON
     * date: 20/01/2018 09:57
     */
    public function findThreeLastInternationale($slug, $offset, $limit)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT a
                            FROM AppBundle:Internationale a
                            WHERE a.statut = :actif
                            AND a.slug <> :slug
                            ORDER BY a.id DESC
                        ')
                        ->setFirstResult($offset)
                        ->setMaxresults($limit)
                        ->setParameters(array(
                            'actif' => 1,
                            'slug'  => $slug
                        ))
                        ->getResult()
                        ;
    }
}
