<?php

namespace AppBundle\Repository;

/**
 * JeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche des trois dernières actualités sans la concernée
     *
     * author: Delrodie AMOIKON
     * date: 20/01/2018 02:54
     */
    public function findThreeLastActucamp($slug, $offset, $limit)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT a
                            FROM AppBundle:Jeu a
                            WHERE a.statut = :actif
                            AND a.slug <> :slug
                            ORDER BY a.id DESC
                        ')
            ->setFirstResult($offset)
            ->setMaxresults($limit)
            ->setParameters(array(
                'actif' => 1,
                'slug'  => $slug
            ))
            ->getResult()
            ;
    }
}
