<?php

namespace AppBundle\Repository;

/**
 * PedagogieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedagogieRepository extends \Doctrine\ORM\EntityRepository
{
}
