<?php

namespace AppBundle\Repository;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche des trois dernières actualités sans la concernée
     * 
     * author: Delrodie AMOIKON
     * date: 25/01/2018 02:20
     */
    public function findPresentation($slug)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                            SELECT a, b
                            FROM AppBundle:Presentation a
                            LEFT JOIN a.typresentation b
                            WHERE a.statut = :actif
                            AND b.slug LIKE :slug
                        ')
                        ->setParameters(array(
                            'actif' => 1,
                            'slug'  => '%'.$slug.'%'
                        ))
                        ->getResult()
                        ;
    }

    /**
     * Verification du slug
     *
     * author: Delrodie AMOIKON
     * date: 10/02/2018 06:27
     */
    public function verifSlug($slug)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery('
                    SELECT p, t
                    FROM AppBundle:Presentation p
                    LEFT JOIN p.typresentation t
                    WHERE p.statut = 1
                    AND t.slug LIKE :slug
                ')
                ->setMaxResults(1)
                ->setParameter('slug', '%'.$slug.'%')
        ;
        if (!$qb->getResult()){
            return $qb->getResult();
        }else{
            return $qb->getSingleResult();
        }
    }
}
