<?php

namespace AppBundle\Repository;

/**
 * RassemblementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RassemblementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche du rassemblement correspondant au slug
     *
     * author: Delrodie AMOIKON
     * date: 07/02/2018 v1.0
     */
    public function findRassemblement($slug){
        $em = $this->getEntityManager();
        $qb = $em->createQuery('
                            SELECT r, t
                            FROM AppBundle:Rassemblement r
                            LEFT JOIN r.typerassemblement t
                            WHERE t.slug LIKE :slug
                            AND r.statut = 1
                            ORDER BY r.id ASC
                        ')
                        ->setParameter('slug', '%'.$slug.'%')
                        ->setMaxResults(1);
                        //->getResult()
                        ; //dump($qb);die();
        if (!$qb->getResult()){
            return [];
        }else{
            return $qb->getSingleResult();
        }

    }

    /**
     * Recherche des autres rassemblements de l'ascci
     *
     * author: Delrodie AMOIKON
     / date: 07/02/2018 15:19
     */
    public function findSimilaire($slug,$offset,$limit){
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                    SELECT r, t
                    FROM AppBundle:Rassemblement r
                    LEFT JOIN r.typerassemblement t 
                    WHERE r.statut = 1
                    AND r.slug <> :slug
                    ORDER BY r.id DESC
                ')
            ->setParameter('slug', $slug)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getResult();
        ;
    }
}
