<?php

namespace AppBundle\Repository;

/**
 * RegionaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionaleRepository extends \Doctrine\ORM\EntityRepository
{
}
