<?php

namespace AppBundle\Repository;

/**
 * RegionpresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionpresentationRepository extends \Doctrine\ORM\EntityRepository
{
}
