<?php

namespace AppBundle\Repository;

/**
 * TypactualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypactualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
