<?php

namespace AppBundle\Repository;

/**
 * TypefonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypefonctionRepository extends \Doctrine\ORM\EntityRepository
{
}
