<?php

namespace AppBundle\Repository;

/**
 * TypenvolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypenvolRepository extends \Doctrine\ORM\EntityRepository
{
}
