<?php

namespace AppBundle\Repository;

/**
 * TyperassemblementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TyperassemblementRepository extends \Doctrine\ORM\EntityRepository
{
}
