<?php

namespace AppBundle\Repository;

/**
 * TypinfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypinfosRepository extends \Doctrine\ORM\EntityRepository
{
}
