<?php

namespace AppBundle\Repository;

/**
 * TypresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypresentationRepository extends \Doctrine\ORM\EntityRepository
{
}
