<?php

namespace AppBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche de la dernière video publiée
     *
     * author: Delrodie AMOIKON
     * date: 13/02/2018 19:31
     */
    public function findVideo($offset,$limit)
    {
        $em = $this->getEntityManager();
        return $qb = $em->createQuery('
                        SELECT v
                        FROM AppBundle:Video v
                        WHERE v.statut = 1
                        ORDER BY v.publieLe DESC
                    ')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getResult();
        ;
    }
}
